### ISSUE TITLE
avro schema converted from type=record to type=object when read from asyncapi

### ISSUE THREAD

**Issue by dennis-brinley** [asyncapi/avro-schema-parser#161]
#### Describe the bug
**avro schema converted from type=record to type=object when read from asyncapi.**

- I have an asyncapi with an avro schema pulled from schema registry. The schema type is "record" with a list of **fields**.
- When the payload is extracted using avro-schema-parser, the record type is changed to "object" with a **properties** list.
- The payload format extracted from the AsyncApi should be consistent with the input.
- Viewing the asyncapi in studio in this manner is not an issue. However, programmatic usage of the payload defined this way is creating a problem.

#### How to Reproduce
We are using the avro-schema-parser to build AsyncApis using schema registry as source for payloads. The behavior can be observed using asyncapi/studio.

1. Using asyncapi/studio at: https://studio.asyncapi.com
2. Paste the following AsyncApi
3. Observe type=Object

**AsyncApi to enter into Studio**
```yaml
---
components:
  schemas: {}
  messages:
    samples.clickstream.avro.ClickEvent:
      payload:
        name: ClickEvent
        namespace: samples.clickstream.avro
        type: record
        fields:
        - name: ip
          type: string
        - name: eventtimestamp
          type: long
        - name: devicetype
          type: string
        - name: event_type
          type:
          - string
          - 'null'
        - name: product_type
          type:
          - string
          - 'null'
        - name: userid
          type: int
        - name: globalseq
          type: long
        - default: 0
          name: prevglobalseq
          type: long
      name: samples.clickstream.avro.ClickEvent
      contentType: application/json
      schemaFormat: application/vnd.apache.avro;version=1.9.0
    default_name:
      payload:
        type: string
      name: default_name
      contentType: application/json
      schemaFormat: application/vnd.apache.avro;version=1.9.0
channels:
  User_Sessions_Aggregates_With_Order_Checkout: {}
  ClickEvents_UserId_Agg_Result: {}
  __amazon_msk_canary: {}
  _schemas: {}
  Departments_Agg: {}
  ExampleTopic:
    publish:
      message:
        "$ref": "#/components/messages/samples.clickstream.avro.ClickEvent"
asyncapi: 2.2.0
info:
  description: API discovery with avro
  title: api_with_avro
  version: 0.1.0
```

**This is the original schema:**
```json
{
	"schema": {
		"type": "record",
		"name": "ClickEvent",
		"namespace": "samples.clickstream.avro",
		"fields": [
			{
				"name": "ip",
				"type": "string"
			},
			{
				"name": "eventtimestamp",
				"type": "long"
			},
			{
				"name": "devicetype",
				"type": "string"
			},
			{
				"name": "event_type",
				"type": [
					"string",
					"null"
				]
			},
			{
				"name": "product_type",
				"type": [
					"string",
					"null"
				]
			},
			{
				"name": "userid",
				"type": "int"
			},
			{
				"name": "globalseq",
				"type": "long"
			},
			{
				"name": "prevglobalseq",
				"type": "long",
				"default": 0
			}
		]
	}
}
```

**This is the output of the avro-schema-parser (schema format extracted from asyncapi)**

- Note the discrepancy between the **type** and **properties/fields**

```json
{
	"type": "object",
	"required": [
		"ip",
		"eventtimestamp",
		"devicetype",
		"userid",
		"globalseq"
	],
	"properties": {
		"ip": {
			"type": "string"
		},
		"eventtimestamp": {
			"type": "integer",
			"minimum": -9223372036854776000,
			"maximum": 9223372036854776000
		},
		"devicetype": {
			"type": "string"
		},
		"event_type": {
			"oneOf": [
				{
					"type": "string"
				},
				{
					"type": "null"
				}
			]
		},
		"product_type": {
			"oneOf": [
				{
					"type": "string"
				},
				{
					"type": "null"
				}
			]
		},
		"userid": {
			"type": "integer",
			"minimum": -2147483648,
			"maximum": 2147483647
		},
		"globalseq": {
			"type": "integer",
			"minimum": -9223372036854776000,
			"maximum": 9223372036854776000
		},
		"prevglobalseq": {
			"type": "integer",
			"minimum": -9223372036854776000,
			"maximum": 9223372036854776000,
			"default": 0
		}
	}
}
```

#### Expected behavior

- The payload format extracted from the AsyncApi should be consistent with the input.
- Payload type: record
- Payload content itemized as fields instead of object properties when input type is "record"

[test-files.zip](https://github.com/asyncapi/avro-schema-parser/files/9610721/test-files.zip)

**Comment by TamimiGitHub** [comment]
Note: See [here](https://docs.oracle.com/cd/E26161_02/html/GettingStartedGuide/avroschemas.html#:~:text=Avro%20schema%20definitions%20are%20JSON,something%20complex%2C%20like%20another%20record) for definition of Avro type record

**Comment by magicmatatjahu** [comment]
@dennis-brinley Hi! AsyncAPI document doesn't "understand" the AVRO schemas so every custom parser (this and also for OpenAPI and RAML) converts data to the corresponding data defined as JSON Schema, and due to this fact, you see `type: object` and `properties` not `type:record, fields:...`, In JSON Schema you don't have `record` type or `fields` keyword.

**Comment by dennis-brinley** [comment]
@magicmatatjahu Hello - I understand the limits of the AsyncApi regarding Avro. The problem that I've described isn't the representation in the AsyncApi itself. Rather, when the AsyncApi is interpreted by avro-schema-parser. AsyncApi containing an Avro schema will be defined using JSON semantics. However, when an asyncapi containing schema with Avro content type is interpreted by the parser, shouldn't it produce an Avro schema that can be used by an application expecting to use that format?

For example, An application requires an Avro schema. Does AsyncApi provide a mechanism to extract the Avro schema content from the payload definition?

Should be:
Avro Schema --embed--> AsyncApi( JSON Semantics ) --extract--> Avro Schema --> Happy Application

The way it is:
Avro Schema --embed--> AsyncApi( JSON Semantics ) --extract--> Json Schema **--X** not-happy Application

**Comment by derberg** [comment]
@dennis-brinley the parser do not remove oryginal info about the payload, these are preserved under:
- `x-parser-original-schema-format` holds information about the original schema format of the payload. You can use different schema formats with the AsyncAPI documents and the parser converts them to AsyncAPI schema. This is why different schema format is set, and the original one is preserved in the extension.
- `x-parser-original-payload` holds the original payload of the message. You can use different formats for payloads with the AsyncAPI documents and the parser converts them to. For example, it converts payload described with Avro schema to AsyncAPI schema. The original payload is preserved in the extension.

I think these could be easily exposed in generated documentation, we could say, payload is avro and provide a way to click and display the original avro schema - is this what you mean?

**Comment by dennis-brinley** [comment]
@derberg - So the intent of extension ```x-parser-original-payload``` is to preserve the raw used to generate the spec? If yes, then then exposing that and value of ```x-parser-original-schema-format``` would be helpful.

So spec would contain something like:
```yaml
messages:
  samples.clickstream.avro.ClickEvent:
    payload:
      name: ClickEvent
      namespace: samples.clickstream.avro
      type: record
      fields:
      - name: ip
        type: string
      # more fields
    name: samples.clickstream.avro.ClickEvent
    contentType: application/json
    schemaFormat: application/vnd.apache.avro;version=1.9.0
    x-parser-original-payload: >
{"type":"record","name":"Payment","namespace":"io.confluent.examples.clients.basicavro","fields":[{"name":"id","type":"string"},{"name":"description","type":"string","default":"my description"},{"name":"amount","type":"double"},{"name":"region","type":"string","default":""},{"name":"testSubject","type":"string","default":""}]}
    x-parser-original-schema-format: application/vnd.apache.avro;version=1.9.0
```

### If this is the case then I'll close the issue.
Either way, it's not a bug :-) Thanks for your help!
